### ISSUE TITLE
Yay

### ISSUE THREAD

**Issue by avalanche1** [AdamBrodzinski/RedScript#9]
Nobody seems to care for this anymore - what a shame..

**Comment by AdamBrodzinski** [comment]
Hi @avalanche1 ! I've been extremely busy and very burnt out from development but it's something I would like to continue with very soon. It's nice to hear feedback as sometimes it feels like no one knows/cares about it 😄 

Cheers
Adam

**Comment by fazibear** [comment]
You know guys, that coffescript is active again. Maybe this one could be a good alternative for that?

**Comment by avalanche1** [comment]
I dont see how they were active except for some weak attempts at making CS compiler produce ES6 output.
As life shows - all community-driven projects burn out eventually.
The only thing left to do for me and Adam is to simply make some millions and then motivate ppl financially to do the projects that we care about.

**Comment by maxyharr** [comment]
How do I get started with redscript? I npm i g redscript and tried compiled, but it just creates a .js file with the same contents. What am I doing wrong?

**Comment by AdamBrodzinski** [comment]
@maxyharr hmmm i'm not sure offhand. If you use the watch like in the readme it should work but to be honest I haven't tried it in over a year.

@avalanche1 FYI I think i'm going to throw in the towel on this project. The final blow is the recent changes to ReasonML 3.0 has all of these features and more, and does an even better job in many aspects. 5 years ago it was better than vanilla ES5 but now that we're getting `|>` in JavaScript soon there's not a lot of features left! 

Maybe one of these days one of us will hit the lottery and then I can work on it while on the beach 😎 🍸 🍺

**Comment by avalanche1** [comment]
Didnot know about REason and pipe operator. 👍
